run without agent alias

diff --git a/.github/workflows/test-waylonwalker-com.yml b/.github/workflows/test-waylonwalker-com.yml
--- a/.github/workflows/test-waylonwalker-com.yml
+++ b/.github/workflows/test-waylonwalker-com.yml
@@ -36,30 +36,29 @@ jobs:
         max_attempts=100
         mkdir -p build/reports/agent
         docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
-        sleep 20
-        # until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
-        #   if [ ${attempt_counter} -eq ${max_attempts} ]; then
-        #     echo "Agent failed to register. Terminating..."
-        #     exit 1
-        #   fi
-        #   attempt_counter=$(($attempt_counter+1))
-        #   echo
-        #   echo
-        #   echo ----------------------------------
-        #   date
-        #   echo attempt $attempt_counter
-        #   echo status
-        #   curl -s http://localhost:8585/api/status || echo "8686 api not up"
-        #   echo status
-        #   curl -s http://localhost:8686/api/status || echo "8686 api not up"
-        #   echo
-        #   echo home
-        #   curl -s http://localhost:8585/ || echo "localhost:8585 is not up"
-        #   echo home
-        #   curl -s http://localhost:8686/ || echo "localhost:8686 is not up"
+        until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
+          if [ ${attempt_counter} -eq ${max_attempts} ]; then
+            echo "Agent failed to register. Terminating..."
+            exit 1
+          fi
+          attempt_counter=$(($attempt_counter+1))
+          echo
+          echo
+          echo ----------------------------------
+          date
+          echo attempt $attempt_counter
+          echo status
+          curl -s http://localhost:8585/api/status || echo "8686 api not up"
+          echo status
+          curl -s http://localhost:8686/api/status || echo "8686 api not up"
+          echo
+          echo home
+          curl -s http://localhost:8585/ || echo "localhost:8585 is not up"
+          echo home
+          curl -s http://localhost:8686/ || echo "localhost:8686 is not up"
 
-        #   sleep 1
-        # done
+          sleep 1
+        done
     - run: pytest > pytest.log
       env:
         TP_DEV_TOKEN: ${{ secrets.TP_DEV_TOKEN }} 
